server: cheroot
host: 0.0.0.0
verbose: 3
logging:
  enable: true
dir_browser:
  enable: false
cors:
  allow_origin: false
http_authenticator:
  accept_basic: true
  accept_digest: true
  default_to_digest: true
provider_mapping:
  "/": "/data"
simple_dc:
  user_mapping:
    "*":
      "admin":
        password: "admin"
