# Uncomment below yaml to override the default configuration (default.config.yaml)
# @see https://wsgidav.readthedocs.io/en/latest/user_guide_configure.html#sample-wsgidav-yaml
#---------------------------------------------------------------------------------------------

# verbose: 3

# logging:
#   enable: true

# dir_browser:
#   enable: false

# cors:
#   allow_origin: false

# http_authenticator:
#   accept_basic: true
#   accept_digest: true
#   default_to_digest: true
#   trusted_auth_header: null
#   domain_controller: wsgidav.dc.simple_dc.SimpleDomainController

# provider_mapping:
#   "/": "/data"
#   "/realm/johndoe": "/data/realm/johndoe"

# Additional options for SimpleDomainController only:
# simple_dc:
#   user_mapping:
#     "*":
#       "admin":
#         password: "f4k3P4$$w0rd"
#     "/realm/johndoe":
#       "johndoe":
#         password: "f4k3P4$$w0rd"
